### ISSUE TITLE
Image must be a gd resource

### ISSUE THREAD

**Issue by eriksachse** [sylvainjule/kirby-colorextractor#13]
Uploaded images (jpg) are giving me the following error: `Image must be a gd resource`

To reproduce: Make photo with iPhone, upload in panel. PNG's not working as well.

Kirby 3.0

**Comment by mingyeungs** [comment]
This happens on PHP 8 due to this dependency [[League\ColorExtractor](https://github.com/thephpleague/color-extractor)], and the issue has been reported [there](https://github.com/thephpleague/color-extractor/issues/64) as well. However it seems that the project is no longer being maintained...

**Comment by sylvainjule** [comment]
Unfortunately, even though the PR fixing this has been noticed, the main contributor to this package from @thephpleague hasn't able to merge it yet: https://github.com/thephpleague/color-extractor/pull/68#issuecomment-913042220

The alternative package that I know of is [color-thief](https://github.com/ksubileau/color-thief-php/), which currently has the same issue: https://github.com/ksubileau/color-thief-php/issues/50

So, I guess it's a waiting game…

**Comment by mattwolff** [comment]
It looks like the latest release of color-thief-php (v2, March 2022) now supports PHP 8.

**Comment by arnoson** [comment]
It seems that the issue in thephpleague/color-extractor has been resolved in version `0.4.0`. But I guess we have to wait until simple image [updates](https://github.com/claviska/SimpleImage/issues/311) color-extractor and then Kirby updates simple image?

**Comment by bnomei** [comment]
i created a PR at that lib today. lets see how that goes.

**Comment by nncrns** [comment]
Any news? The issues at simple image has been closed, meaning that this plugin could now be updated?

**Comment by johannesverwoerd** [comment]
I am also curious to know if this great plugin will be updated. Thanks!
