### ISSUE TITLE
Field method toColor('average') returns the dominant color in extract mode => 'both'

### ISSUE THREAD

**Issue by houdini-rites** [sylvainjule/kirby-colorextractor#15]
I am using `'sylvainjule.colorextractor.mode' => 'both'` to extract both the dominant and the average color. 

It seems to work and `$image->color()` returns a comma-separated list with both colors:

```
Kirby\Cms\Field Object
(
    [color] => #5F99A5,#7B8992
)
```
However when I try using the field methods `$image->color()->toColor('dominant')` and `$image->color()->toColor('average')` I only get the dominant color as a result in both cases.

**Comment by sylvainjule** [comment]
Unfortunately I cannot reproduce this, it works as intended on my installs. 
What is the Kirby version?

**Comment by houdini-rites** [comment]
Hi, I am using Kirby 3.6.2. 

I looked again and figured out that I only encounter this issue when hananils's [kirby colors](https://github.com/hananils/kirby-colors) is in the plugins folder as well (I intended to use both plugins together). 

Here is a demo: [https://github.com/houdini-rites/color-extractor-test](https://github.com/houdini-rites/color-extractor-test)

For me with this setup `$image->color()->toColor('dominant')` and `$image->color()->toColor('average')` return two different colors only after I remove hananils's color picker plugin from the plugins folder.

I am not sure if this is an incompatibility issue or I am doing something wrong..

Thank you for looking into it!

**Comment by sylvainjule** [comment]
There is a conflict as the `toColor` method name is already used by hananils' plugin. I will change it.

**Comment by sylvainjule** [comment]
I have changed it, you should now use `->dominantColor()` or `->averageColor()`.

**Comment by houdini-rites** [comment]
Thank you!
