### ISSUE TITLE
PHP Notice:  Use of undefined constant DS

### ISSUE THREAD

**Issue by joernroeder** [sylvainjule/kirby-colorextractor#2]
I'm getting the error on a fresh install of kirby beta6.1, running in arch linux docker container.

adding `if (!defined('DS')) define('DS', DIRECTORY_SEPARATOR);` to `index.php` before vendors get loaded via the autoloader fixed it for me.

**Comment by sylvainjule** [comment]
sounds good! I've made the change, if it happens again I'll replace it with a forward slash.
