### ISSUE TITLE
`'mode' => 'both'` resizes image at 1 * 2px

### ISSUE THREAD

**Issue by apademide** [sylvainjule/kirby-colorextractor#20]
I was setting up the plugin and testing the different extraction modes. For some reason, setting `'sylvainjule.colorextractor.mode' => 'both'` caused images to be resized to 1 by 2px.
 
I can't give you extensive context and didn't check all the combinations, but switching to `dominant` fixed the issue so it might either be caused by `both` specifically or `average` on its own. My gut feeling would be that `average`'s logic at some point resizes the image down to 1px to get the color, and actually applies the resize on the original image rather than a copy.

While `both` was selected, both uploaded images and images on which `extractColor` was called were resized.

**Comment by apademide** [comment]
After switching to only `dominant`, it actually stopped resizing to 1px... in favour of 300px. This time I actually opened the plugin's source to find these two lines, where the exact same values appear. 

Removing the plugin also fixes the issue, so I can tell for sure there's an issue somewhere in the implementation that causes the file source to be resized instead of a copy. 

```php
if(in_array($mode, ['dominant', 'both'])) {
    $colors[] = static::processImage($image, 300, $fallbackColor);
}
if(in_array($mode, ['average', 'both'])) {
    $colors[] = static::processImage($image, 1, $fallbackColor);
}
```

**Comment by bnomei** [comment]
https://github.com/sylvainjule/kirby-colorextractor/blob/ce59c04d90e170fff0c76fee061e866a65db257c/lib/colorextractor.php#L30

`resize` in k4 does not create a copy but directly modified the image.

**Comment by apademide** [comment]
Was actually a local issue due to a custom override in the `file::version` component.
