### ISSUE TITLE
Call to a member function find() on array

### ISSUE THREAD

**Issue by tobystokes** [sylvainjule/kirby-colorextractor#7]
when i try to 'Extract missing colors' using the field, 
after the message: 'There are 3 images without any color extracted, do you want to process them now?' I get:
'3 images processed, with 3 error(s)'
Call to a member function find() on array (x 3)

Uploading a single image seems to work ok - I get the color value stoered for that, it's jsut for multiples it seems.
 
```
code: 500
exception: "Error"
file: "plugins/colorextractor/lib/routes.php"
line: 10
message: "Call to a member function find() on array"
route: "colorextractor/process-image"
```

versions:
    "getkirby/cms": "3.1.2",
    "sylvainjule/colorextractor": "1.0.1"

**Comment by joernroeder** [comment]
@sylvainjule thanks for fixing the issue! would you mind releasing a new version as well so that composer will pick up the changes too? thx

**Comment by sylvainjule** [comment]
My bad, just released one :)
