### ISSUE TITLE
Kirby 3.4 compatibility

### ISSUE THREAD

**Issue by nilshoerrmann** [sylvainjule/kirby-colorextractor#9]
The hook migration checker for Kirby 3.4 reports and issue for this plugin:

<img width="645" alt="grafik" src="https://user-images.githubusercontent.com/25466/86587546-195ae200-bf8a-11ea-91d7-9225a28062ae.png">

See https://github.com/getkirby/kirby/releases/tag/3.4.0-rc.1

**Comment by sylvainjule** [comment]
Fixed by #10
